image: bradrydzewski/go:1.4
git:
  path: github.com/mikejihbe/gotest2
script:
  - echo "build commands"
  - bin/build
  - bin/test
publish:
  docker:
    dockerfile: ./Dockerfile
    docker_host: 10.10.10.15:2375
    docker_version: 1.4.1
    registry_login_url: $$bintray_repo_login_url
    registry_login: true
    username: $$bintray_user
    password: $$bintray_api_key
    email: $$bintray_user_email
    image_name: $$bintray_image_name
    push_latest: true
    tag: $DRONE_COMMIT
notify:
  webhook:
    urls:
      - "http://shipped-api.tx3.shipped-cisco.com/webhooks/drone"
    on_success: true
    on_failure: true
